[project]
authors = ["Ibrahim Ahmed"]
entry = "main.sw"
license = "Apache-2.0"
name = "bridgemodule"

[dependencies]
yama_interfaces = { path = "../yama_interfaces" }
bytes_extended = { path = "../hyperlane_contracts/bytes-extended" }
hyperlane_interfaces = { path = "../hyperlane_contracts/hyperlane-interfaces" }
stablecoin_library = { path = "../stablecoin_library" }