[workspace]
members = [
  'bridgemodule',
  'balancesheetmodule',
  'cdpmodule',
  'dutchauctionliquidator',
  'emptycollateralmanager',
  'modulartoken',
  'pegstabilitymodule',
  'psmpricesource',
  'flashmintmodule',
  'simplebsh',
  'psmlockup',
  'leverageproxy'
]