[project]
authors = ["Ibrahim"]
entry = "main.sw"
license = "Apache-2.0"
name = "dutchauctionliquidator"

[dependencies]
stablecoin_library = { path = "../stablecoin_library" }
yama_types = { path = "../yama_types" }
yama_interfaces = { path = "../yama_interfaces" }
signed_integers = { git = "https://github.com/FuelLabs/sway-libs", tag="v0.7.1" }
fixed_point = { git = "https://github.com/FuelLabs/sway-libs", tag="v0.7.1" }