use fuels::{prelude::*};

abigen!(
    Contract(
        name="BalanceSheet",
        abi="../balancesheetmodule/out/debug/balancesheetmodule-abi.json"
    ),
    Contract(
        name="CDP",
        abi="../cdpmodule/out/debug/cdpmodule-abi.json"
    ),
    Contract(
        name="DutchAuctionLiquidator",
        abi="../dutchauctionliquidator/out/debug/dutchauctionliquidator-abi.json"
    ),
    Contract(
        name="EmptyCollateralManager",
        abi="../emptycollateralmanager/out/debug/emptycollateralmanager-abi.json"
    ),
    Contract(
        name="ModularToken",
        abi="../modulartoken/out/debug/modulartoken-abi.json"
    ),
    Contract(
        name="PSM",
        abi="../pegstabilitymodule/out/debug/pegstabilitymodule-abi.json"
    ),
    Contract(
        name="PSMPriceSource",
        abi="../psmpricesource/out/debug/psmpricesource-abi.json"
    ),
    Contract(
        name="SimpleBSH",
        abi="../simplebsh/out/debug/simplebsh-abi.json"
    ),
    Contract(
        name="PSMLockup",
        abi="../psmlockup/out/debug/psmlockup-abi.json"
    ),
    Contract(
        name="FlashMintModule",
        abi="../flashmintmodule/out/debug/flashmintmodule-abi.json"
    ),
    Contract(
        name="LeverageProxy",
        abi="../leverageproxy/out/debug/leverageproxy-abi.json"
    ),
    Contract(
        name="BridgeModule",
        abi="../bridgemodule/out/debug/bridgemodule-abi.json"
    ),
    Contract(
        name="TestSwapper",
        abi="../testswapper/out/debug/testswapper-abi.json"
    )
);