[project]
authors = ["Goliath"]
entry = "lib.sw"
license = "Unlicensed"
name = "stablecoin_library"

[dependencies]
signed_integers = { git = "https://github.com/FuelLabs/sway-libs", tag="v0.7.1" }
fixed_point = { git = "https://github.com/FuelLabs/sway-libs", tag="v0.7.1" }
yama_interfaces = { path = "../yama_interfaces" }
yama_types = { path = "../yama_types" }