[project]
authors = ["Ibrahim Ahmed"]
entry = "main.sw"
license = "Apache-2.0"
name = "flashmintmodule"

[dependencies]
yama_interfaces = { path = "../yama_interfaces" }
stablecoin_library = { path = "../stablecoin_library" }