[project]
authors = ["Goliath"]
entry = "main.sw"
license = "Unlicensed"
name = "modulartoken"

[dependencies]
yama_interfaces = { path = "../yama_interfaces" }
stablecoin_library = { path = "../stablecoin_library" }