[project]
authors = ["Goliath"]
entry = "main.sw"
license = "Apache-2.0"
name = "balancesheetmodule"

[dependencies]
stablecoin_library = { path = "../stablecoin_library" }
yama_interfaces = { path = "../yama_interfaces" }
signed_integers = { git = "https://github.com/FuelLabs/sway-libs", tag="v0.7.1" }