[project]
authors = ["Ibrahim Ahmed"]
entry = "main.sw"
license = "Apache-2.0"
name = "simplebsh"

[dependencies]
yama_interfaces = { path = "../yama_interfaces" }
stablecoin_library = { path = "../stablecoin_library" }
signed_integers = { git = "https://github.com/FuelLabs/sway-libs", tag="v0.7.1" }